catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - packages-lib/*

catalog:
  domq.js: ^0.7.1
  rollup: ^4.60.0
  rollup-plugin-md: ^1.0.1

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - utf-8-validate
