packages:
  - packages/*
  - packages-lib/*

catalog:
  '@rollup/plugin-node-resolve': ^15.3.1
  '@rollup/plugin-replace': ^5.0.7
  '@rsbuild/core': ^1.7.5
  baseline-browser-mapping: ^2.10.20
  bulma: ^1.0.4
  comlink: ^4.4.2
  cross-env: ^10.0.0
  domq.js: ^0.7.1
  file-saver: ^2.0.5
  less: ^4.6.4
  open: ^8.4.2
  plop: ^4.0.4
  postcss: ^8.5.10
  rollup: ^4.60.2
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-html-string: ^1.0.1
  rollup-plugin-livereload: ^2.0.5
  rollup-plugin-md: ^1.0.1
  rollup-plugin-monkey: ^1.0.9
  rollup-plugin-postcss: ^4.0.2
  rollup-plugin-serve: ^2.0.3
  sass: ^1.99.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  vite: ^7.3.2
  vite-plugin-monkey: ^7.1.9

catalogMode: prefer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - esbuild
  - utf-8-validate

shellEmulator: true

trustPolicy: no-downgrade
catalogs:
  conflicts_rollup_h3_30_0:
    rollup: ^3.30.0
