name: Build
on:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
      - 'site-astro/**'
jobs:
  def:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      # Install pipenv and dependencies
      - name: Install pipenv and dependencies
        run: |
          pip3 install --user pipenv
          pipenv --python python3 && pipenv install
      # Get Post Changes
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      # List all changed files
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      # Build README
      - name: Build README
        env:
          GIT_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          pipenv run build
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Install Deps && Build Astro
      - name: Install Deps && Build Astro
        run: |
          cd site-astro
          npm install
          npm run build
          # 写入 .nojekyll 到 docs 目录
          cd .. && touch docs/.nojekyll
      # Commit Changes To Git
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          # git diff-index --quiet HEAD || (git commit -m "Auto Commit" -a --no-verify)
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto Commit" -a --no-verify
          fi
      # Push Changes To Git
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
