name: readme
on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai # https://xirikm.net/2020/215-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      # - name: Get file changes
      #   id: file_changes
      #   uses: trilom/file-changes-action@v1.2.4
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     # output: '" "'
      # - name: _cache_logs
      #   env:
      #     _cache_logs: ${{ steps.file_changes.outputs.files }}
      #   run: |
      #     echo ${_cache_logs}
      - name: Build
        # env:
        #   _cache_logs: ${{ steps.file_changes.outputs.files }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git diff-index --quiet HEAD || (git commit -m "Auto Commit" -a --no-verify)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
